apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-prosessering
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 8000
  liveness:
    path: /isAlive
    initialDelay: 5
  readiness:
    path: /isReady
    initialDelay: 5
  replicas:
    min: 1
    max: 1
  ingresses:
    - "https://dp-prosessering.intern.dev.nav.no"
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      allowAllUsers: true
      replyURLs:
        - 'https://dp-prosessering.intern.dev.nav.no/auth/openid/callback'
  accessPolicy:
    outbound:
      rules:
        - application: dp-iverksett
  resources:
    limits:
      memory: 1024Mi
    requests:
      memory: 512Mi
  envFrom:
    - secret: dp-prosessering
  env:
    - name: ENV
      value: dev