apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tilleggsstonader-prosessering
  namespace: tilleggsstonader
  labels:
    team: tilleggsstonader
spec:
  image: {{ image }}
  team: tilleggsstonader
  port: 8000
  liveness:
    path: /isAlive
    initialDelay: 5
  readiness:
    path: /isReady
    initialDelay: 5
  replicas:
    min: 1
    max: 1
  ingresses:
    - "https://tilleggsstonader-prosessering.intern.dev.nav.no"
  azure:
    application:
      enabled: true
      allowAllUsers: true
      replyURLs:
        - 'https://tilleggsstonader-prosessering.intern.dev.nav.no/auth/openid/callback'
  accessPolicy:
    outbound:
      rules:
        - application: tilleggsstonader-sak
        - application: tilleggsstonader-soknad-api
  resources:
    limits:
      memory: 1024Mi
    requests:
      memory: 512Mi
  envFrom:
    - secret: prosessering
  env:
    - name: ENV
      value: dev