apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: familie-prosessering
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  team: teamfamilie
  port: 8000
  liveness:
    path: /isAlive
    initialDelay: 5
  readiness:
    path: /isReady
    initialDelay: 5
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  ingresses:
    - "https://familie-prosessering.dev-adeo.no"
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      memory: 512Mi