apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: utsjekk-prosessering
  namespace: helved
  labels:
    team: helved
spec:
  image: {{ image }}
  port: 8000
  liveness:
    path: /isAlive
    initialDelay: 5
  readiness:
    path: /isReady
    initialDelay: 5
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  ingresses:
    - "https://utsjekk-prosessering.intern.nav.no"
  azure:
    application:
      enabled: true
      replyURLs:
        - 'https://utsjekk-prosessering.intern.nav.no/auth/openid/callback'
  accessPolicy:
    outbound:
      rules:
        - application: utsjekk
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 256Mi
      cpu: 20m
  envFrom:
    - secret: utsjekk-prosessering
  env:
    - name: ENV
      value: prod