name: Build and deploy dp-prosessering to prod

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: yarn
          registry-url: "https://npm.pkg.github.com"
      - name: Yarn install
        run: yarn --prefer-offline --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Yarn build
        run: yarn build
      - name: Build and publish Docker image to GAR
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: teamdagpenger
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
  deploy-dev:
    name: Deploy to Dev - Dagpenger
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY_DAGPENGER }}
          CLUSTER: dev-gcp
          RESOURCE: build_n_deploy/naiserator/gcp-dev-dagpenger.yaml
          VAR: image=${{ needs.build.outputs.image }}
  deploy-dagpenger:
    name: Deploy to Prod - Dagpenger
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY_DAGPENGER }}
          CLUSTER: prod-gcp
          RESOURCE: build_n_deploy/naiserator/gcp-prod-dagpenger.yaml
          VAR: image=${{ needs.build.outputs.image }}
